use_frameworks!

platform :ios, '8.0'

target 'PDModelKVMapper_Example' do
  pod 'PDModelKVMapper', :path => '../'

  target 'PDModelKVMapper_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
